apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-test
  namespace: default
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  storage:
    size: 1Gi
