// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Check if the API is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    }
                }
            }
        },
        "/databases": {
            "get": {
                "description": "Get a list of all PostgreSQL database clusters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "List all database clusters",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DatabaseListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new CloudNativePG database cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "Create a new PostgreSQL database cluster",
                "parameters": [
                    {
                        "description": "Database creation request",
                        "name": "database",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DatabaseCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.DatabaseInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/databases/{name}": {
            "get": {
                "description": "Get detailed information about a specific database cluster",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "Get database cluster information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DatabaseInfo"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Permanently delete a database cluster and all its data",
                "tags": [
                    "databases"
                ],
                "summary": "Delete a database cluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Database deleted successfully"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update database cluster configuration (instances, storage)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "Update database cluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update request",
                        "name": "update",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DatabaseUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DatabaseInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/databases/{name}/credentials": {
            "get": {
                "description": "Get connection credentials for a database cluster",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "Get database credentials",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DatabaseCredentials"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.HealthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.DatabaseCreateRequest": {
            "type": "object",
            "required": [
                "instances",
                "name",
                "postgresql_version",
                "storage_size"
            ],
            "properties": {
                "instances": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1
                },
                "name": {
                    "type": "string",
                    "maxLength": 253,
                    "minLength": 1
                },
                "postgresql_version": {
                    "type": "integer",
                    "maximum": 18,
                    "minimum": 12
                },
                "storage_size": {
                    "type": "string"
                },
                "tenantId": {
                    "type": "string"
                }
            }
        },
        "models.DatabaseCredentials": {
            "type": "object",
            "properties": {
                "connection_string": {
                    "type": "string"
                },
                "database": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.DatabaseInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "instances": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "postgresql_version": {
                    "type": "string"
                },
                "ready_instances": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/models.DatabaseStatus"
                },
                "storage_size": {
                    "type": "string"
                }
            }
        },
        "models.DatabaseListResponse": {
            "type": "object",
            "properties": {
                "databases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DatabaseInfo"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.DatabaseStatus": {
            "type": "string",
            "enum": [
                "ready",
                "creating",
                "failed",
                "deleting",
                "unknown"
            ],
            "x-enum-varnames": [
                "StatusReady",
                "StatusCreating",
                "StatusFailed",
                "StatusDeleting",
                "StatusUnknown"
            ]
        },
        "models.DatabaseUpdateRequest": {
            "type": "object",
            "properties": {
                "instances": {
                    "type": "integer"
                },
                "storage_size": {
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
