apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-custom-queries
  namespace: postgres-clusters
data:
  queries: |
    pg_database_size:
      query: "SELECT datname, pg_database_size(datname) as size_bytes FROM pg_database"
      metrics:
        - datname: {usage: "LABEL", description: "Name of the database"}
        - size_bytes: {usage: "GAUGE", description: "Disk space in bytes"}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-global-podmonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - postgres-clusters
  selector:
    matchExpressions:
      - key: cnpg.io/cluster
        operator: Exists
  podMetricsEndpoints:
    - port: metrics
      targetPort: 9187
      interval: 30s
      path: /metrics
      scheme: http
